services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $adherentInterests: '%adherent_interests%'

    App\Twig\:
        resource: ../../src/Twig/

    App\Twig\AssetRuntime:
        arguments:
            $secret: '%kernel.secret%'
            $env: '%kernel.environment%'
            $hash: '%assets_hash%'
            $symfonyAssetExtension: '@twig.extension.assets'

    App\Twig\MunicipalSiteRuntime:
        arguments:
            $cache: !service
                class: Symfony\Component\Cache\Simple\Psr6Cache
                arguments:
                    - '@app.cache.municipal_site'

    App\Twig\CanaryExtension:
        $canaryMode: '%env(ENABLE_CANARY)%'
