services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $adherentInterests: '%adherent_interests%'

    App\Twig\:
        resource: ../../src/Twig/

    App\Twig\AssetRuntime:
        arguments:
            $secret: '%kernel.secret%'
            $appVersion: '%env(APP_VERSION)%'
            $symfonyAssetExtension: '@twig.extension.assets'
            $mimeTypes: '@mime_types'

    App\Twig\CanaryExtension:
        $canaryMode: '%env(ENABLE_CANARY)%'
