<?php

namespace App\DataFixtures\ORM;

use App\Entity\Skill;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

class LoadSkillData implements FixtureInterface
{
    const SKILLS = [
        'S001' => 'Software',
        'S002' => 'Analyze',
        'S003' => 'Mathématiques',
        'S004' => 'Statistique',
        'S005' => 'Ecriture médiatique',
        'S006' => 'Gestion des relations',
        'S007' => 'Culture de l\'image',
        'S008' => 'Outils médias',
        'S009' => 'Médecine',
        'S010' => 'Psychologie',
        'S011' => 'Animation d\'une équipe',
    ];

    const SKILL_CI = [
        'Agriculture',
        'Elevage',
        'Culture',
        'Architecture',
        'Arts',
        'Peinture',
        'Sculpture',
        'Décoration',
        'Musique',
        'Théâtre',
        'Dessin',
        'Photographie',
        'Cirque',
        'Pêche',
        'Soins aux animaux',
        'Nature et Environnement',
        'Paysage',
        'Jardinage/Botanique',
        'Gestion des parcs nationaux',
        'Isolation thermique et acoustique',
        'Horticulture',
        'Gestion des déchets',
        'Communication/Marketing/Médias',
        'Organisation d\'événements',
        'Gestion de la presse',
        'Relations publiques',
        'Supports de communication ',
        'Veille',
        'Community management',
        'Plan média',
        'Reportage',
        'Rédaction d\'articles',
        'Conception de contenus multimédias',
        'Enquêtes de satisfaction',
        'Mailings',
        'Comptabilité',
        'Finance',
        'Levée de fonds',
        'Elaboration de budget',
        'Audit',
        'Ingénieur/Technicien',
        'Peinture',
        'Conduite de chantier',
        'Maçonnerie',
        'Plomberie',
        'Construction/Travaux',
        'Electricité',
        'Droit',
        'Droit du patrimoine',
        'Droit pénal',
        'Droit des pensions civiles et militaires de retraite',
        'Droit des pensions de retraite des marins français du commerce, de pêche ou de plaisance',
        'Droit des pensions militaires d\'invalidité et des victimes de la guerre',
        'Droit des ports maritimes',
        'Droit des postes et des communications électroniques',
        'Droit de la propriété intellectuelle',
        'Droit de la recherche',
        'Droit de la route',
        'Droit rural et de la pêche maritime',
        'Droit de la santé publique',
        'Droit de la sécurité intérieure',
        'Droit de la sécurité sociale',
        'Droit du service national',
        'Droit du sport',
        'Droit du tourisme',
        'Droit du travail (... à Mayotte)',
        'Droit du travail maritime',
        'Droit de l\'urbanisme',
        'Droit de la voirie routière',
        'Conseil juridique',
        'Contentieux',
        'Rédaction d\'actes juridiques',
        'Veille juridique',
        'Education',
        'Cours de Mathématiques',
        'Cours de Philosophie',
        'Cours d\'Histoire/Géo',
        'Cours de SVT',
        'Cours de Français',
        'Cours d\'Anglais',
        'Cours d\'Espagnol',
        'Cours d\'Arabe',
        'Cours d\'Hébreu',
        'Cours de Géométrie',
        'Cours de Chinois',
        'Cours d\'Italien',
        'Cours de guitare',
        'Cours de Yoga',
        'Graphisme',
        'Conception de logo, brochure, etc',
        'Hôtellerie',
        'Restauration',
        'Chef cuisinier',
        'Restauration rapide',
        'Pâtisserie',
        'Tourisme/loisirs',
        'Animation',
        'BAFA',
        'Enfants',
        'Tous publics',
        'Clown',
        'Cuisine',
        'Informatique/Numérique/Digital',
        'Création d\'un site Internet',
        'Programmation web/code (PHP, Java, SQL, ASP, etc.)',
        'Gestion de bases de données',
        'Développement d\'applications',
        'Santé',
        'Médecin',
        'Infirmier-e',
        'Aide-soignant',
        'Psychologue',
        'Secouriste',
        'Lien social',
        'Conversation',
        'Assistance aux personnes âgées',
        'Traduction',
        'Français - Chinois',
        'Français - Anglais',
        'Français – Espagnol',
        'Français - Hindi',
        'Français – Allemand',
        'Français - Russe',
        'Français - Malais-indonésien',
        'Français - Arabe',
        'Français - Portugais',
        'Français - Bengali',
    ];

    public function load(ObjectManager $manager)
    {
        foreach (self::SKILLS as $name) {
            $manager->persist(new Skill($name));
        }

        $manager->flush();
    }
}
