kreait_firebase:
    projects:
        jemarche_app:
            credentials: '%kernel.project_dir%/gcloud-service-key.json'

services:
    Kreait\Firebase\Messaging: '@kreait_firebase.jemarche_app.messaging'
