league_oauth2_server:
    authorization_server:
        private_key: '%env(resolve:OAUTH_PRIVATE_KEY)%'
        encryption_key: '%env(resolve:OAUTH_ENCRYPTION_KEY)%'
        encryption_key_type: defuse # One of "plain"; "defuse"

        access_token_ttl: PT1H
        refresh_token_ttl: P1M
        auth_code_ttl: PT10M

        enable_client_credentials_grant: false
        enable_password_grant: false
        enable_implicit_grant: false

    #        require_code_challenge_for_public_clients: true
    #        persist_access_token: true
    resource_server:
        public_key: '%env(resolve:OAUTH_PUBLIC_KEY)%'
    scopes:
        available: ['user']
        default: ['user']
    persistence:
        doctrine: null
    role_prefix: ROLE_OAUTH2_
    client:
        classname: App\Entity\OAuth\Client

when@test:
    league_oauth2_server:
        persistence:
            in_memory: null
