framework:
    rate_limiter:
        activation_account_retry:
            policy: 'sliding_window'
            limit: 3
            interval: '1 minute'

        change_email:
            policy: 'sliding_window'
            limit: 3
            interval: '5 minutes'

        ohme_api_request:
            policy: 'fixed_window'
            limit: 100
            interval: '1 minute'
