scheb_two_factor:
    google:
        enabled: true
        issuer: En Marche !
        template: security/admin_google_authenticator.html.twig
    security_tokens:
         - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
