framework:
    default_locale: '%locale%'
    enabled_locales: ['%locale%', 'en']
    translator:
        paths:
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
