vich_uploader:
    db_driver: orm
    storage: flysystem
    metadata:
        type: attribute
    mappings:
        uploadable_file:
            uri_prefix: /assets
            upload_destination: default.storage
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
            delete_on_update: false
            delete_on_remove: true
