framework:
    workflows:
        ton_macron_invitation:
            type: state_machine
            supports: [App\TonMacron\InvitationProcessor]
            places:
                - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INFO
                - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_PROJECT
                - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INTERESTS
                - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_SELF_REASONS
                - !php/const App\TonMacron\InvitationProcessor::STATE_SUMMARY
                - !php/const App\TonMacron\InvitationProcessor::STATE_SENT
            transitions:
                !php/const App\TonMacron\InvitationProcessor::TRANSITION_FILL_INFO:
                    from:
                        - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INFO
                    to: !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_PROJECT
                !php/const App\TonMacron\InvitationProcessor::TRANSITION_FILL_PROJECT:
                    from:
                        - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_PROJECT
                    to: !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INTERESTS
                !php/const App\TonMacron\InvitationProcessor::TRANSITION_FILL_INTERESTS:
                    from:
                        - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INTERESTS
                    to: !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_SELF_REASONS
                !php/const App\TonMacron\InvitationProcessor::TRANSITION_FILL_REASONS:
                    from:
                        - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_SELF_REASONS
                    to: !php/const App\TonMacron\InvitationProcessor::STATE_SUMMARY
                !php/const App\TonMacron\InvitationProcessor::TRANSITION_SEND:
                    from:
                        - !php/const App\TonMacron\InvitationProcessor::STATE_SUMMARY
                    to: !php/const App\TonMacron\InvitationProcessor::STATE_SENT
        my_europe:
            type: state_machine
            supports: [App\Interactive\MyEuropeProcessor]
            places:
                - !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_INFO
                - !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_CASES
                - !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_APPRECIATIONS
                - !php/const App\Interactive\MyEuropeProcessor::STATE_SUMMARY
                - !php/const App\Interactive\MyEuropeProcessor::STATE_SENT
            transitions:
                !php/const App\Interactive\MyEuropeProcessor::TRANSITION_FILL_INFO:
                    from:
                        - !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_INFO
                    to: !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_CASES
                !php/const App\Interactive\MyEuropeProcessor::TRANSITION_FILL_CASES:
                    from:
                        - !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_CASES
                    to: !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_APPRECIATIONS
                !php/const App\Interactive\MyEuropeProcessor::TRANSITION_FILL_APPRECIATIONS:
                    from:
                        - !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_APPRECIATIONS
                    to: !php/const App\Interactive\MyEuropeProcessor::STATE_SUMMARY
                !php/const App\Interactive\MyEuropeProcessor::TRANSITION_SEND:
                    from:
                        - !php/const App\Interactive\MyEuropeProcessor::STATE_SUMMARY
                    to: !php/const App\Interactive\MyEuropeProcessor::STATE_SENT

        assessor_request:
            type: state_machine
            initial_place: !php/const App\Assessor\AssessorRequestEnum::STATE_PERSONAL_INFO
            supports: [App\Assessor\AssessorRequestCommand]
            places:
                - !php/const App\Assessor\AssessorRequestEnum::STATE_PERSONAL_INFO
                - !php/const App\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO
                - !php/const App\Assessor\AssessorRequestEnum::STATE_SUMMARY
                - !php/const App\Assessor\AssessorRequestEnum::STATE_REQUEST_SENT
            transitions:
                !php/const App\Assessor\AssessorRequestEnum::TRANSITION_FILL_PERSONAL_INFO:
                    from:
                        - !php/const App\Assessor\AssessorRequestEnum::STATE_PERSONAL_INFO
                    to: !php/const App\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO

                !php/const App\Assessor\AssessorRequestEnum::TRANSITION_FILL_ASSESSOR_INFO:
                    from:
                        - !php/const App\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO
                    to: !php/const App\Assessor\AssessorRequestEnum::STATE_SUMMARY

                !php/const App\Assessor\AssessorRequestEnum::TRANSITION_VALID_SUMMARY:
                    from:
                        - !php/const App\Assessor\AssessorRequestEnum::STATE_SUMMARY
                    to: !php/const App\Assessor\AssessorRequestEnum::STATE_REQUEST_SENT

                !php/const App\Assessor\AssessorRequestEnum::TRANSITION_BACK_ASSESSOR_INFO:
                    from:
                        - !php/const App\Assessor\AssessorRequestEnum::STATE_SUMMARY
                    to : !php/const App\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO

                !php/const App\Assessor\AssessorRequestEnum::TRANSITION_BACK_PERSONAL_INFO:
                    from:
                        - !php/const App\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO
                    to : !php/const App\Assessor\AssessorRequestEnum::STATE_PERSONAL_INFO
        voting_process:
            type: 'state_machine'
            marking_store:
                type: 'single_state'
                arguments:
                    - 'state'
            initial_place: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::INITIALIZE
            supports:
                - App\VotingPlatform\Election\VoteCommand\VoteCommand
            places:
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::INITIALIZE
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::START
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::VOTE
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::FINISH
            transitions:
                !php/const App\VotingPlatform\Election\VoteCommandStateEnum::TO_START:
                    from:
                        - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::INITIALIZE
                        - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::VOTE
                        - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                    to: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::START
                !php/const App\VotingPlatform\Election\VoteCommandStateEnum::TO_VOTE:
                    from:
                        - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::START
                        - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                    to: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::VOTE
                !php/const App\VotingPlatform\Election\VoteCommandStateEnum::TO_CONFIRM:
                    from: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::VOTE
                    to: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                !php/const App\VotingPlatform\Election\VoteCommandStateEnum::TO_FINISH:
                    from: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                    to: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::FINISH
