framework:
    workflows:
        ton_macron_invitation:
            type: state_machine
            supports: [App\TonMacron\InvitationProcessor]
            marking_store:
                type: 'method'
                property: 'marking'
            places:
                - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INFO
                - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_PROJECT
                - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INTERESTS
                - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_SELF_REASONS
                - !php/const App\TonMacron\InvitationProcessor::STATE_SUMMARY
                - !php/const App\TonMacron\InvitationProcessor::STATE_SENT
            transitions:
                !php/const App\TonMacron\InvitationProcessor::TRANSITION_FILL_INFO:
                    from:
                        - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INFO
                    to: !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_PROJECT
                !php/const App\TonMacron\InvitationProcessor::TRANSITION_FILL_PROJECT:
                    from:
                        - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_PROJECT
                    to: !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INTERESTS
                !php/const App\TonMacron\InvitationProcessor::TRANSITION_FILL_INTERESTS:
                    from:
                        - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_FRIEND_INTERESTS
                    to: !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_SELF_REASONS
                !php/const App\TonMacron\InvitationProcessor::TRANSITION_FILL_REASONS:
                    from:
                        - !php/const App\TonMacron\InvitationProcessor::STATE_NEEDS_SELF_REASONS
                    to: !php/const App\TonMacron\InvitationProcessor::STATE_SUMMARY
                !php/const App\TonMacron\InvitationProcessor::TRANSITION_SEND:
                    from:
                        - !php/const App\TonMacron\InvitationProcessor::STATE_SUMMARY
                    to: !php/const App\TonMacron\InvitationProcessor::STATE_SENT

        my_europe:
            type: state_machine
            supports: [App\Interactive\MyEuropeProcessor]
            marking_store:
                type: 'method'
                property: 'marking'
            places:
                - !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_INFO
                - !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_CASES
                - !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_APPRECIATIONS
                - !php/const App\Interactive\MyEuropeProcessor::STATE_SUMMARY
                - !php/const App\Interactive\MyEuropeProcessor::STATE_SENT
            transitions:
                !php/const App\Interactive\MyEuropeProcessor::TRANSITION_FILL_INFO:
                    from:
                        - !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_INFO
                    to: !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_CASES
                !php/const App\Interactive\MyEuropeProcessor::TRANSITION_FILL_CASES:
                    from:
                        - !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_CASES
                    to: !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_APPRECIATIONS
                !php/const App\Interactive\MyEuropeProcessor::TRANSITION_FILL_APPRECIATIONS:
                    from:
                        - !php/const App\Interactive\MyEuropeProcessor::STATE_NEEDS_FRIEND_APPRECIATIONS
                    to: !php/const App\Interactive\MyEuropeProcessor::STATE_SUMMARY
                !php/const App\Interactive\MyEuropeProcessor::TRANSITION_SEND:
                    from:
                        - !php/const App\Interactive\MyEuropeProcessor::STATE_SUMMARY
                    to: !php/const App\Interactive\MyEuropeProcessor::STATE_SENT

        assessor_request:
            type: state_machine
            initial_marking: !php/const App\Assessor\AssessorRequestEnum::STATE_PERSONAL_INFO
            supports: [App\Assessor\AssessorRequestCommand]
            marking_store:
                type: 'method'
                property: 'marking'
            places:
                - !php/const App\Assessor\AssessorRequestEnum::STATE_PERSONAL_INFO
                - !php/const App\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO
                - !php/const App\Assessor\AssessorRequestEnum::STATE_SUMMARY
                - !php/const App\Assessor\AssessorRequestEnum::STATE_REQUEST_SENT
            transitions:
                !php/const App\Assessor\AssessorRequestEnum::TRANSITION_FILL_PERSONAL_INFO:
                    from:
                        - !php/const App\Assessor\AssessorRequestEnum::STATE_PERSONAL_INFO
                    to: !php/const App\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO

                !php/const App\Assessor\AssessorRequestEnum::TRANSITION_FILL_ASSESSOR_INFO:
                    from:
                        - !php/const App\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO
                    to: !php/const App\Assessor\AssessorRequestEnum::STATE_SUMMARY

                !php/const App\Assessor\AssessorRequestEnum::TRANSITION_VALID_SUMMARY:
                    from:
                        - !php/const App\Assessor\AssessorRequestEnum::STATE_SUMMARY
                    to: !php/const App\Assessor\AssessorRequestEnum::STATE_REQUEST_SENT

                !php/const App\Assessor\AssessorRequestEnum::TRANSITION_BACK_ASSESSOR_INFO:
                    from:
                        - !php/const App\Assessor\AssessorRequestEnum::STATE_SUMMARY
                    to : !php/const App\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO

                !php/const App\Assessor\AssessorRequestEnum::TRANSITION_BACK_PERSONAL_INFO:
                    from:
                        - !php/const App\Assessor\AssessorRequestEnum::STATE_ASSESSOR_INFO
                    to : !php/const App\Assessor\AssessorRequestEnum::STATE_PERSONAL_INFO

        voting_process:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'state'
            initial_marking: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::INITIALIZE
            supports:
                - App\VotingPlatform\Election\VoteCommand\VoteCommand
            places:
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::INITIALIZE
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::START
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::VOTE
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::FINISH
            transitions:
                !php/const App\VotingPlatform\Election\VoteCommandStateEnum::TO_START:
                    from:
                        - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::INITIALIZE
                        - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::VOTE
                        - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                    to: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::START
                !php/const App\VotingPlatform\Election\VoteCommandStateEnum::TO_VOTE:
                    from:
                        - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::START
                        - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                    to: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::VOTE
                !php/const App\VotingPlatform\Election\VoteCommandStateEnum::TO_CONFIRM:
                    from: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::VOTE
                    to: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                !php/const App\VotingPlatform\Election\VoteCommandStateEnum::TO_FINISH:
                    from: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                    to: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::FINISH

        contribution_request:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'state'
            initial_marking: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_START
            supports:
                - App\Adherent\Contribution\ContributionRequest
            places:
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_START
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_NO_CONTRIBUTION_NEEDED
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_CONTRIBUTION_ALREADY_DONE
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_REVENUE
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_SEE_CONTRIBUTION_AMOUNT
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_CONTRIBUTION_INFORMATIONS
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_CONTRIBUTION_COMPLETE
            transitions:
                !php/const App\Adherent\Contribution\ContributionRequestStateEnum::TO_FILL_REVENUE:
                    from:
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_START
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_REVENUE
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_NO_CONTRIBUTION_NEEDED
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_SEE_CONTRIBUTION_AMOUNT
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_CONTRIBUTION_INFORMATIONS
                    to: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_REVENUE

                !php/const App\Adherent\Contribution\ContributionRequestStateEnum::TO_NO_CONTRIBUTION_NEEDED:
                    from:
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_REVENUE
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_NO_CONTRIBUTION_NEEDED
                    to: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_NO_CONTRIBUTION_NEEDED

                !php/const App\Adherent\Contribution\ContributionRequestStateEnum::TO_CONTRIBUTION_ALREADY_DONE:
                    from:
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_REVENUE
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_CONTRIBUTION_ALREADY_DONE
                    to: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_CONTRIBUTION_ALREADY_DONE

                !php/const App\Adherent\Contribution\ContributionRequestStateEnum::TO_SEE_CONTRIBUTION_AMOUNT:
                    from:
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_SEE_CONTRIBUTION_AMOUNT
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_REVENUE
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_CONTRIBUTION_INFORMATIONS
                    to: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_SEE_CONTRIBUTION_AMOUNT

                !php/const App\Adherent\Contribution\ContributionRequestStateEnum::TO_FILL_CONTRIBUTION_INFORMATIONS:
                    from:
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_CONTRIBUTION_INFORMATIONS
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_SEE_CONTRIBUTION_AMOUNT
                    to: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_CONTRIBUTION_INFORMATIONS

                !php/const App\Adherent\Contribution\ContributionRequestStateEnum::TO_CONTRIBUTION_COMPLETE:
                    from:
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_CONTRIBUTION_COMPLETE
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_CONTRIBUTION_INFORMATIONS
                    to: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_CONTRIBUTION_COMPLETE
