framework:
    workflows:
        voting_process:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'state'
            initial_marking: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::INITIALIZE
            supports:
                - App\VotingPlatform\Election\VoteCommand\VoteCommand
            places:
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::INITIALIZE
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::VOTE
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::FINISH
            transitions:
                !php/const App\VotingPlatform\Election\VoteCommandStateEnum::TO_VOTE:
                    from:
                        - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::INITIALIZE
                        - !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                    to: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::VOTE
                !php/const App\VotingPlatform\Election\VoteCommandStateEnum::TO_CONFIRM:
                    from: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::VOTE
                    to: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                !php/const App\VotingPlatform\Election\VoteCommandStateEnum::TO_FINISH:
                    from: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::CONFIRM
                    to: !php/const App\VotingPlatform\Election\VoteCommandStateEnum::FINISH

        contribution_process:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'state'
            initial_marking: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_START
            supports:
                - App\Adherent\Contribution\ContributionRequest
            places:
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_START
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_NO_CONTRIBUTION_NEEDED
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_CONTRIBUTION_ALREADY_DONE
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_REVENUE
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_SEE_CONTRIBUTION_AMOUNT
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_CONTRIBUTION_INFORMATIONS
                - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_CONTRIBUTION_COMPLETE
            transitions:
                !php/const App\Adherent\Contribution\ContributionRequestStateEnum::TO_FILL_REVENUE:
                    from:
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_START
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_REVENUE
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_NO_CONTRIBUTION_NEEDED
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_SEE_CONTRIBUTION_AMOUNT
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_CONTRIBUTION_INFORMATIONS
                    to: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_REVENUE

                !php/const App\Adherent\Contribution\ContributionRequestStateEnum::TO_NO_CONTRIBUTION_NEEDED:
                    from:
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_REVENUE
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_NO_CONTRIBUTION_NEEDED
                    to: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_NO_CONTRIBUTION_NEEDED

                !php/const App\Adherent\Contribution\ContributionRequestStateEnum::TO_CONTRIBUTION_ALREADY_DONE:
                    from:
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_REVENUE
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_CONTRIBUTION_ALREADY_DONE
                    to: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_CONTRIBUTION_ALREADY_DONE

                !php/const App\Adherent\Contribution\ContributionRequestStateEnum::TO_SEE_CONTRIBUTION_AMOUNT:
                    from:
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_SEE_CONTRIBUTION_AMOUNT
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_REVENUE
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_CONTRIBUTION_INFORMATIONS
                    to: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_SEE_CONTRIBUTION_AMOUNT

                !php/const App\Adherent\Contribution\ContributionRequestStateEnum::TO_FILL_CONTRIBUTION_INFORMATIONS:
                    from:
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_CONTRIBUTION_INFORMATIONS
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_SEE_CONTRIBUTION_AMOUNT
                    to: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_CONTRIBUTION_INFORMATIONS

                !php/const App\Adherent\Contribution\ContributionRequestStateEnum::TO_CONTRIBUTION_COMPLETE:
                    from:
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_CONTRIBUTION_COMPLETE
                        - !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_FILL_CONTRIBUTION_INFORMATIONS
                    to: !php/const App\Adherent\Contribution\ContributionRequestStateEnum::STATE_CONTRIBUTION_COMPLETE
