services:
    app:
        image: ${REGISTRY}:${TAG}-${HASH}
        user: root
        environment:
            APP_ENV: test

    db:
        tmpfs: /var/lib/mysql

    rabbitmq:
        image: rabbitmq:3-alpine

    selenium:
        ports:
            - 5900:5900
