<?php

namespace AppBundle\Repository;

/**
 * LegislativeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegislativeRepository extends \Doctrine\ORM\EntityRepository
{
}
