<?php

namespace AppBundle\Repository;

/**
 * MediaPathRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaPathRepository extends \Doctrine\ORM\EntityRepository
{
}
