<?php

namespace AppBundle\Repository;

/**
 * NewsletterSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
