<?php

namespace Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20190826105021 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE SEQUENCE citizen_projects_id_seq');
        $this->addSql('SELECT setval(\'citizen_projects_id_seq\', (SELECT MAX(id) FROM citizen_projects))');
        $this->addSql('ALTER TABLE citizen_projects ALTER id SET DEFAULT nextval(\'citizen_projects_id_seq\')');
        $this->addSql('CREATE SEQUENCE adherents_id_seq');
        $this->addSql('SELECT setval(\'adherents_id_seq\', (SELECT MAX(id) FROM adherents))');
        $this->addSql('ALTER TABLE adherents ALTER id SET DEFAULT nextval(\'adherents_id_seq\')');
        $this->addSql('CREATE SEQUENCE committees_id_seq');
        $this->addSql('SELECT setval(\'committees_id_seq\', (SELECT MAX(id) FROM committees))');
        $this->addSql('ALTER TABLE committees ALTER id SET DEFAULT nextval(\'committees_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_idea_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_idea_id_seq\', (SELECT MAX(id) FROM ideas_workshop_idea))');
        $this->addSql('ALTER TABLE ideas_workshop_idea ALTER id SET DEFAULT nextval(\'ideas_workshop_idea_id_seq\')');
        $this->addSql('CREATE SEQUENCE procuration_requests_id_seq');
        $this->addSql('SELECT setval(\'procuration_requests_id_seq\', (SELECT MAX(id) FROM procuration_requests))');
        $this->addSql('ALTER TABLE procuration_requests ALTER id SET DEFAULT nextval(\'procuration_requests_id_seq\')');
        $this->addSql('CREATE SEQUENCE referent_id_seq');
        $this->addSql('SELECT setval(\'referent_id_seq\', (SELECT MAX(id) FROM referent))');
        $this->addSql('ALTER TABLE referent ALTER id SET DEFAULT nextval(\'referent_id_seq\')');
        $this->addSql('CREATE SEQUENCE reports_id_seq');
        $this->addSql('SELECT setval(\'reports_id_seq\', (SELECT MAX(id) FROM reports))');
        $this->addSql('ALTER TABLE reports ALTER id SET DEFAULT nextval(\'reports_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_comment_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_comment_id_seq\', (SELECT MAX(id) FROM ideas_workshop_comment))');
        $this->addSql('ALTER TABLE ideas_workshop_comment ALTER id SET DEFAULT nextval(\'ideas_workshop_comment_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_thread_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_thread_id_seq\', (SELECT MAX(id) FROM ideas_workshop_thread))');
        $this->addSql('ALTER TABLE ideas_workshop_thread ALTER id SET DEFAULT nextval(\'ideas_workshop_thread_id_seq\')');
        $this->addSql('CREATE SEQUENCE turnkey_projects_id_seq');
        $this->addSql('SELECT setval(\'turnkey_projects_id_seq\', (SELECT MAX(id) FROM turnkey_projects))');
        $this->addSql('ALTER TABLE turnkey_projects ALTER id SET DEFAULT nextval(\'turnkey_projects_id_seq\')');
        $this->addSql('CREATE SEQUENCE articles_id_seq');
        $this->addSql('SELECT setval(\'articles_id_seq\', (SELECT MAX(id) FROM articles))');
        $this->addSql('ALTER TABLE articles ALTER id SET DEFAULT nextval(\'articles_id_seq\')');
        $this->addSql('CREATE SEQUENCE proposals_id_seq');
        $this->addSql('SELECT setval(\'proposals_id_seq\', (SELECT MAX(id) FROM proposals))');
        $this->addSql('ALTER TABLE proposals ALTER id SET DEFAULT nextval(\'proposals_id_seq\')');
        $this->addSql('CREATE SEQUENCE order_articles_id_seq');
        $this->addSql('SELECT setval(\'order_articles_id_seq\', (SELECT MAX(id) FROM order_articles))');
        $this->addSql('ALTER TABLE order_articles ALTER id SET DEFAULT nextval(\'order_articles_id_seq\')');
        $this->addSql('CREATE SEQUENCE mooc_id_seq');
        $this->addSql('SELECT setval(\'mooc_id_seq\', (SELECT MAX(id) FROM mooc))');
        $this->addSql('ALTER TABLE mooc ALTER id SET DEFAULT nextval(\'mooc_id_seq\')');
        $this->addSql('CREATE SEQUENCE adherent_messages_id_seq');
        $this->addSql('SELECT setval(\'adherent_messages_id_seq\', (SELECT MAX(id) FROM adherent_messages))');
        $this->addSql('ALTER TABLE adherent_messages ALTER id SET DEFAULT nextval(\'adherent_messages_id_seq\')');
        $this->addSql('CREATE SEQUENCE assessor_requests_id_seq');
        $this->addSql('SELECT setval(\'assessor_requests_id_seq\', (SELECT MAX(id) FROM assessor_requests))');
        $this->addSql('ALTER TABLE assessor_requests ALTER id SET DEFAULT nextval(\'assessor_requests_id_seq\')');
        $this->addSql('CREATE SEQUENCE vote_place_id_seq');
        $this->addSql('SELECT setval(\'vote_place_id_seq\', (SELECT MAX(id) FROM vote_place))');
        $this->addSql('ALTER TABLE vote_place ALTER id SET DEFAULT nextval(\'vote_place_id_seq\')');
        $this->addSql('CREATE SEQUENCE biography_executive_office_member_id_seq');
        $this->addSql('SELECT setval(\'biography_executive_office_member_id_seq\', (SELECT MAX(id) FROM biography_executive_office_member))');
        $this->addSql('ALTER TABLE biography_executive_office_member ALTER id SET DEFAULT nextval(\'biography_executive_office_member_id_seq\')');
        $this->addSql('CREATE SEQUENCE events_id_seq');
        $this->addSql('SELECT setval(\'events_id_seq\', (SELECT MAX(id) FROM events))');
        $this->addSql('ALTER TABLE events ALTER id SET DEFAULT nextval(\'events_id_seq\')');
        $this->addSql('CREATE SEQUENCE turnkey_projects_files_id_seq');
        $this->addSql('SELECT setval(\'turnkey_projects_files_id_seq\', (SELECT MAX(id) FROM turnkey_projects_files))');
        $this->addSql('ALTER TABLE turnkey_projects_files ALTER id SET DEFAULT nextval(\'turnkey_projects_files_id_seq\')');
        $this->addSql('CREATE SEQUENCE committee_feed_item_id_seq');
        $this->addSql('SELECT setval(\'committee_feed_item_id_seq\', (SELECT MAX(id) FROM committee_feed_item))');
        $this->addSql('ALTER TABLE committee_feed_item ALTER id SET DEFAULT nextval(\'committee_feed_item_id_seq\')');
        $this->addSql('CREATE SEQUENCE pages_id_seq');
        $this->addSql('SELECT setval(\'pages_id_seq\', (SELECT MAX(id) FROM pages))');
        $this->addSql('ALTER TABLE pages ALTER id SET DEFAULT nextval(\'pages_id_seq\')');
        $this->addSql('CREATE SEQUENCE clarifications_id_seq');
        $this->addSql('SELECT setval(\'clarifications_id_seq\', (SELECT MAX(id) FROM clarifications))');
        $this->addSql('ALTER TABLE clarifications ALTER id SET DEFAULT nextval(\'clarifications_id_seq\')');
        $this->addSql('CREATE SEQUENCE donations_id_seq');
        $this->addSql('SELECT setval(\'donations_id_seq\', (SELECT MAX(id) FROM donations))');
        $this->addSql('ALTER TABLE donations ALTER id SET DEFAULT nextval(\'donations_id_seq\')');
        $this->addSql('CREATE SEQUENCE formation_modules_id_seq');
        $this->addSql('SELECT setval(\'formation_modules_id_seq\', (SELECT MAX(id) FROM formation_modules))');
        $this->addSql('ALTER TABLE formation_modules ALTER id SET DEFAULT nextval(\'formation_modules_id_seq\')');
        $this->addSql('CREATE SEQUENCE interactive_invitations_id_seq');
        $this->addSql('SELECT setval(\'interactive_invitations_id_seq\', (SELECT MAX(id) FROM interactive_invitations))');
        $this->addSql('ALTER TABLE interactive_invitations ALTER id SET DEFAULT nextval(\'interactive_invitations_id_seq\')');
        $this->addSql('CREATE SEQUENCE jecoute_survey_id_seq');
        $this->addSql('SELECT setval(\'jecoute_survey_id_seq\', (SELECT MAX(id) FROM jecoute_survey))');
        $this->addSql('ALTER TABLE jecoute_survey ALTER id SET DEFAULT nextval(\'jecoute_survey_id_seq\')');
        $this->addSql('CREATE SEQUENCE jecoute_survey_question_id_seq');
        $this->addSql('SELECT setval(\'jecoute_survey_question_id_seq\', (SELECT MAX(id) FROM jecoute_survey_question))');
        $this->addSql('ALTER TABLE jecoute_survey_question ALTER id SET DEFAULT nextval(\'jecoute_survey_question_id_seq\')');
        $this->addSql('CREATE SEQUENCE adherent_activation_keys_id_seq');
        $this->addSql('SELECT setval(\'adherent_activation_keys_id_seq\', (SELECT MAX(id) FROM adherent_activation_keys))');
        $this->addSql('ALTER TABLE adherent_activation_keys ALTER id SET DEFAULT nextval(\'adherent_activation_keys_id_seq\')');
        $this->addSql('CREATE SEQUENCE procuration_proxies_id_seq');
        $this->addSql('SELECT setval(\'procuration_proxies_id_seq\', (SELECT MAX(id) FROM procuration_proxies))');
        $this->addSql('ALTER TABLE procuration_proxies ALTER id SET DEFAULT nextval(\'procuration_proxies_id_seq\')');
        $this->addSql('CREATE SEQUENCE organizational_chart_item_id_seq');
        $this->addSql('SELECT setval(\'organizational_chart_item_id_seq\', (SELECT MAX(id) FROM organizational_chart_item))');
        $this->addSql('ALTER TABLE organizational_chart_item ALTER id SET DEFAULT nextval(\'organizational_chart_item_id_seq\')');
        $this->addSql('CREATE SEQUENCE administrators_id_seq');
        $this->addSql('SELECT setval(\'administrators_id_seq\', (SELECT MAX(id) FROM administrators))');
        $this->addSql('ALTER TABLE administrators ALTER id SET DEFAULT nextval(\'administrators_id_seq\')');
        $this->addSql('CREATE SEQUENCE adherent_reset_password_tokens_id_seq');
        $this->addSql('SELECT setval(\'adherent_reset_password_tokens_id_seq\', (SELECT MAX(id) FROM adherent_reset_password_tokens))');
        $this->addSql('ALTER TABLE adherent_reset_password_tokens ALTER id SET DEFAULT nextval(\'adherent_reset_password_tokens_id_seq\')');
        $this->addSql('CREATE SEQUENCE adherent_change_email_token_id_seq');
        $this->addSql('SELECT setval(\'adherent_change_email_token_id_seq\', (SELECT MAX(id) FROM adherent_change_email_token))');
        $this->addSql('ALTER TABLE adherent_change_email_token ALTER id SET DEFAULT nextval(\'adherent_change_email_token_id_seq\')');
        $this->addSql('CREATE SEQUENCE social_share_categories_id_seq');
        $this->addSql('SELECT setval(\'social_share_categories_id_seq\', (SELECT MAX(id) FROM social_share_categories))');
        $this->addSql('ALTER TABLE social_share_categories ALTER id SET DEFAULT nextval(\'social_share_categories_id_seq\')');
        $this->addSql('CREATE SEQUENCE ton_macron_friend_invitations_id_seq');
        $this->addSql('SELECT setval(\'ton_macron_friend_invitations_id_seq\', (SELECT MAX(id) FROM ton_macron_friend_invitations))');
        $this->addSql('ALTER TABLE ton_macron_friend_invitations ALTER id SET DEFAULT nextval(\'ton_macron_friend_invitations_id_seq\')');
        $this->addSql('CREATE SEQUENCE legislative_candidates_id_seq');
        $this->addSql('SELECT setval(\'legislative_candidates_id_seq\', (SELECT MAX(id) FROM legislative_candidates))');
        $this->addSql('ALTER TABLE legislative_candidates ALTER id SET DEFAULT nextval(\'legislative_candidates_id_seq\')');
        $this->addSql('CREATE SEQUENCE mooc_attachment_file_id_seq');
        $this->addSql('SELECT setval(\'mooc_attachment_file_id_seq\', (SELECT MAX(id) FROM mooc_attachment_file))');
        $this->addSql('ALTER TABLE mooc_attachment_file ALTER id SET DEFAULT nextval(\'mooc_attachment_file_id_seq\')');
        $this->addSql('CREATE SEQUENCE user_documents_id_seq');
        $this->addSql('SELECT setval(\'user_documents_id_seq\', (SELECT MAX(id) FROM user_documents))');
        $this->addSql('ALTER TABLE user_documents ALTER id SET DEFAULT nextval(\'user_documents_id_seq\')');
        $this->addSql('CREATE SEQUENCE board_member_id_seq');
        $this->addSql('SELECT setval(\'board_member_id_seq\', (SELECT MAX(id) FROM board_member))');
        $this->addSql('ALTER TABLE board_member ALTER id SET DEFAULT nextval(\'board_member_id_seq\')');
        $this->addSql('CREATE SEQUENCE events_invitations_id_seq');
        $this->addSql('SELECT setval(\'events_invitations_id_seq\', (SELECT MAX(id) FROM events_invitations))');
        $this->addSql('ALTER TABLE events_invitations ALTER id SET DEFAULT nextval(\'events_invitations_id_seq\')');
        $this->addSql('CREATE SEQUENCE referent_managed_users_message_id_seq');
        $this->addSql('SELECT setval(\'referent_managed_users_message_id_seq\', (SELECT MAX(id) FROM referent_managed_users_message))');
        $this->addSql('ALTER TABLE referent_managed_users_message ALTER id SET DEFAULT nextval(\'referent_managed_users_message_id_seq\')');
        $this->addSql('CREATE SEQUENCE referent_person_link_id_seq');
        $this->addSql('SELECT setval(\'referent_person_link_id_seq\', (SELECT MAX(id) FROM referent_person_link))');
        $this->addSql('ALTER TABLE referent_person_link ALTER id SET DEFAULT nextval(\'referent_person_link_id_seq\')');
        $this->addSql('CREATE SEQUENCE redirections_id_seq');
        $this->addSql('SELECT setval(\'redirections_id_seq\', (SELECT MAX(id) FROM redirections))');
        $this->addSql('ALTER TABLE redirections ALTER id SET DEFAULT nextval(\'redirections_id_seq\')');
        $this->addSql('CREATE SEQUENCE jecoute_managed_areas_id_seq');
        $this->addSql('SELECT setval(\'jecoute_managed_areas_id_seq\', (SELECT MAX(id) FROM jecoute_managed_areas))');
        $this->addSql('ALTER TABLE jecoute_managed_areas ALTER id SET DEFAULT nextval(\'jecoute_managed_areas_id_seq\')');
        $this->addSql('CREATE SEQUENCE web_hooks_id_seq');
        $this->addSql('SELECT setval(\'web_hooks_id_seq\', (SELECT MAX(id) FROM web_hooks))');
        $this->addSql('ALTER TABLE web_hooks ALTER id SET DEFAULT nextval(\'web_hooks_id_seq\')');
        $this->addSql('CREATE SEQUENCE districts_id_seq');
        $this->addSql('SELECT setval(\'districts_id_seq\', (SELECT MAX(id) FROM districts))');
        $this->addSql('ALTER TABLE districts ALTER id SET DEFAULT nextval(\'districts_id_seq\')');
        $this->addSql('CREATE SEQUENCE subscription_type_id_seq');
        $this->addSql('SELECT setval(\'subscription_type_id_seq\', (SELECT MAX(id) FROM subscription_type))');
        $this->addSql('ALTER TABLE subscription_type ALTER id SET DEFAULT nextval(\'subscription_type_id_seq\')');
        $this->addSql('CREATE SEQUENCE referent_space_access_information_id_seq');
        $this->addSql('SELECT setval(\'referent_space_access_information_id_seq\', (SELECT MAX(id) FROM referent_space_access_information))');
        $this->addSql('ALTER TABLE referent_space_access_information ALTER id SET DEFAULT nextval(\'referent_space_access_information_id_seq\')');
        $this->addSql('CREATE SEQUENCE proposals_themes_id_seq');
        $this->addSql('SELECT setval(\'proposals_themes_id_seq\', (SELECT MAX(id) FROM proposals_themes))');
        $this->addSql('ALTER TABLE proposals_themes ALTER id SET DEFAULT nextval(\'proposals_themes_id_seq\')');
        $this->addSql('CREATE SEQUENCE timeline_manifestos_id_seq');
        $this->addSql('SELECT setval(\'timeline_manifestos_id_seq\', (SELECT MAX(id) FROM timeline_manifestos))');
        $this->addSql('ALTER TABLE timeline_manifestos ALTER id SET DEFAULT nextval(\'timeline_manifestos_id_seq\')');
        $this->addSql('CREATE SEQUENCE timeline_themes_id_seq');
        $this->addSql('SELECT setval(\'timeline_themes_id_seq\', (SELECT MAX(id) FROM timeline_themes))');
        $this->addSql('ALTER TABLE timeline_themes ALTER id SET DEFAULT nextval(\'timeline_themes_id_seq\')');
        $this->addSql('CREATE SEQUENCE timeline_measures_id_seq');
        $this->addSql('SELECT setval(\'timeline_measures_id_seq\', (SELECT MAX(id) FROM timeline_measures))');
        $this->addSql('ALTER TABLE timeline_measures ALTER id SET DEFAULT nextval(\'timeline_measures_id_seq\')');
        $this->addSql('CREATE SEQUENCE timeline_profiles_id_seq');
        $this->addSql('SELECT setval(\'timeline_profiles_id_seq\', (SELECT MAX(id) FROM timeline_profiles))');
        $this->addSql('ALTER TABLE timeline_profiles ALTER id SET DEFAULT nextval(\'timeline_profiles_id_seq\')');
        $this->addSql('CREATE SEQUENCE geo_data_id_seq');
        $this->addSql('SELECT setval(\'geo_data_id_seq\', (SELECT MAX(id) FROM geo_data))');
        $this->addSql('ALTER TABLE geo_data ALTER id SET DEFAULT nextval(\'geo_data_id_seq\')');
        $this->addSql('CREATE SEQUENCE newsletter_invitations_id_seq');
        $this->addSql('SELECT setval(\'newsletter_invitations_id_seq\', (SELECT MAX(id) FROM newsletter_invitations))');
        $this->addSql('ALTER TABLE newsletter_invitations ALTER id SET DEFAULT nextval(\'newsletter_invitations_id_seq\')');
        $this->addSql('CREATE SEQUENCE coordinator_managed_areas_id_seq');
        $this->addSql('SELECT setval(\'coordinator_managed_areas_id_seq\', (SELECT MAX(id) FROM coordinator_managed_areas))');
        $this->addSql('ALTER TABLE coordinator_managed_areas ALTER id SET DEFAULT nextval(\'coordinator_managed_areas_id_seq\')');
        $this->addSql('CREATE SEQUENCE ton_macron_choices_id_seq');
        $this->addSql('SELECT setval(\'ton_macron_choices_id_seq\', (SELECT MAX(id) FROM ton_macron_choices))');
        $this->addSql('ALTER TABLE ton_macron_choices ALTER id SET DEFAULT nextval(\'ton_macron_choices_id_seq\')');
        $this->addSql('CREATE SEQUENCE committees_memberships_id_seq');
        $this->addSql('SELECT setval(\'committees_memberships_id_seq\', (SELECT MAX(id) FROM committees_memberships))');
        $this->addSql('ALTER TABLE committees_memberships ALTER id SET DEFAULT nextval(\'committees_memberships_id_seq\')');
        $this->addSql('CREATE SEQUENCE invitations_id_seq');
        $this->addSql('SELECT setval(\'invitations_id_seq\', (SELECT MAX(id) FROM invitations))');
        $this->addSql('ALTER TABLE invitations ALTER id SET DEFAULT nextval(\'invitations_id_seq\')');
        $this->addSql('CREATE SEQUENCE mooc_elements_id_seq');
        $this->addSql('SELECT setval(\'mooc_elements_id_seq\', (SELECT MAX(id) FROM mooc_elements))');
        $this->addSql('ALTER TABLE mooc_elements ALTER id SET DEFAULT nextval(\'mooc_elements_id_seq\')');
        $this->addSql('CREATE SEQUENCE mooc_attachment_link_id_seq');
        $this->addSql('SELECT setval(\'mooc_attachment_link_id_seq\', (SELECT MAX(id) FROM mooc_attachment_link))');
        $this->addSql('ALTER TABLE mooc_attachment_link ALTER id SET DEFAULT nextval(\'mooc_attachment_link_id_seq\')');
        $this->addSql('CREATE SEQUENCE mooc_chapter_id_seq');
        $this->addSql('SELECT setval(\'mooc_chapter_id_seq\', (SELECT MAX(id) FROM mooc_chapter))');
        $this->addSql('ALTER TABLE mooc_chapter ALTER id SET DEFAULT nextval(\'mooc_chapter_id_seq\')');
        $this->addSql('CREATE SEQUENCE je_marche_reports_id_seq');
        $this->addSql('SELECT setval(\'je_marche_reports_id_seq\', (SELECT MAX(id) FROM je_marche_reports))');
        $this->addSql('ALTER TABLE je_marche_reports ALTER id SET DEFAULT nextval(\'je_marche_reports_id_seq\')');
        $this->addSql('CREATE SEQUENCE custom_search_results_id_seq');
        $this->addSql('SELECT setval(\'custom_search_results_id_seq\', (SELECT MAX(id) FROM custom_search_results))');
        $this->addSql('ALTER TABLE custom_search_results ALTER id SET DEFAULT nextval(\'custom_search_results_id_seq\')');
        $this->addSql('CREATE SEQUENCE municipal_chief_areas_id_seq');
        $this->addSql('SELECT setval(\'municipal_chief_areas_id_seq\', (SELECT MAX(id) FROM municipal_chief_areas))');
        $this->addSql('ALTER TABLE municipal_chief_areas ALTER id SET DEFAULT nextval(\'municipal_chief_areas_id_seq\')');
        $this->addSql('CREATE SEQUENCE adherent_message_filters_id_seq');
        $this->addSql('SELECT setval(\'adherent_message_filters_id_seq\', (SELECT MAX(id) FROM adherent_message_filters))');
        $this->addSql('ALTER TABLE adherent_message_filters ALTER id SET DEFAULT nextval(\'adherent_message_filters_id_seq\')');
        $this->addSql('CREATE SEQUENCE mailchimp_campaign_report_id_seq');
        $this->addSql('SELECT setval(\'mailchimp_campaign_report_id_seq\', (SELECT MAX(id) FROM mailchimp_campaign_report))');
        $this->addSql('ALTER TABLE mailchimp_campaign_report ALTER id SET DEFAULT nextval(\'mailchimp_campaign_report_id_seq\')');
        $this->addSql('CREATE SEQUENCE mailchimp_campaign_id_seq');
        $this->addSql('SELECT setval(\'mailchimp_campaign_id_seq\', (SELECT MAX(id) FROM mailchimp_campaign))');
        $this->addSql('ALTER TABLE mailchimp_campaign ALTER id SET DEFAULT nextval(\'mailchimp_campaign_id_seq\')');
        $this->addSql('CREATE SEQUENCE citizen_project_memberships_id_seq');
        $this->addSql('SELECT setval(\'citizen_project_memberships_id_seq\', (SELECT MAX(id) FROM citizen_project_memberships))');
        $this->addSql('ALTER TABLE citizen_project_memberships ALTER id SET DEFAULT nextval(\'citizen_project_memberships_id_seq\')');
        $this->addSql('CREATE SEQUENCE oauth_clients_id_seq');
        $this->addSql('SELECT setval(\'oauth_clients_id_seq\', (SELECT MAX(id) FROM oauth_clients))');
        $this->addSql('ALTER TABLE oauth_clients ALTER id SET DEFAULT nextval(\'oauth_clients_id_seq\')');
        $this->addSql('CREATE SEQUENCE oauth_access_tokens_id_seq');
        $this->addSql('SELECT setval(\'oauth_access_tokens_id_seq\', (SELECT MAX(id) FROM oauth_access_tokens))');
        $this->addSql('ALTER TABLE oauth_access_tokens ALTER id SET DEFAULT nextval(\'oauth_access_tokens_id_seq\')');
        $this->addSql('CREATE SEQUENCE oauth_refresh_tokens_id_seq');
        $this->addSql('SELECT setval(\'oauth_refresh_tokens_id_seq\', (SELECT MAX(id) FROM oauth_refresh_tokens))');
        $this->addSql('ALTER TABLE oauth_refresh_tokens ALTER id SET DEFAULT nextval(\'oauth_refresh_tokens_id_seq\')');
        $this->addSql('CREATE SEQUENCE oauth_auth_codes_id_seq');
        $this->addSql('SELECT setval(\'oauth_auth_codes_id_seq\', (SELECT MAX(id) FROM oauth_auth_codes))');
        $this->addSql('ALTER TABLE oauth_auth_codes ALTER id SET DEFAULT nextval(\'oauth_auth_codes_id_seq\')');
        $this->addSql('CREATE SEQUENCE user_authorizations_id_seq');
        $this->addSql('SELECT setval(\'user_authorizations_id_seq\', (SELECT MAX(id) FROM user_authorizations))');
        $this->addSql('ALTER TABLE user_authorizations ALTER id SET DEFAULT nextval(\'user_authorizations_id_seq\')');
        $this->addSql('CREATE SEQUENCE live_links_id_seq');
        $this->addSql('SELECT setval(\'live_links_id_seq\', (SELECT MAX(id) FROM live_links))');
        $this->addSql('ALTER TABLE live_links ALTER id SET DEFAULT nextval(\'live_links_id_seq\')');
        $this->addSql('CREATE SEQUENCE chez_vous_departments_id_seq');
        $this->addSql('SELECT setval(\'chez_vous_departments_id_seq\', (SELECT MAX(id) FROM chez_vous_departments))');
        $this->addSql('ALTER TABLE chez_vous_departments ALTER id SET DEFAULT nextval(\'chez_vous_departments_id_seq\')');
        $this->addSql('CREATE SEQUENCE chez_vous_markers_id_seq');
        $this->addSql('SELECT setval(\'chez_vous_markers_id_seq\', (SELECT MAX(id) FROM chez_vous_markers))');
        $this->addSql('ALTER TABLE chez_vous_markers ALTER id SET DEFAULT nextval(\'chez_vous_markers_id_seq\')');
        $this->addSql('CREATE SEQUENCE chez_vous_regions_id_seq');
        $this->addSql('SELECT setval(\'chez_vous_regions_id_seq\', (SELECT MAX(id) FROM chez_vous_regions))');
        $this->addSql('ALTER TABLE chez_vous_regions ALTER id SET DEFAULT nextval(\'chez_vous_regions_id_seq\')');
        $this->addSql('CREATE SEQUENCE chez_vous_cities_id_seq');
        $this->addSql('SELECT setval(\'chez_vous_cities_id_seq\', (SELECT MAX(id) FROM chez_vous_cities))');
        $this->addSql('ALTER TABLE chez_vous_cities ALTER id SET DEFAULT nextval(\'chez_vous_cities_id_seq\')');
        $this->addSql('CREATE SEQUENCE chez_vous_measures_id_seq');
        $this->addSql('SELECT setval(\'chez_vous_measures_id_seq\', (SELECT MAX(id) FROM chez_vous_measures))');
        $this->addSql('ALTER TABLE chez_vous_measures ALTER id SET DEFAULT nextval(\'chez_vous_measures_id_seq\')');
        $this->addSql('CREATE SEQUENCE failed_login_attempt_id_seq');
        $this->addSql('SELECT setval(\'failed_login_attempt_id_seq\', (SELECT MAX(id) FROM failed_login_attempt))');
        $this->addSql('ALTER TABLE failed_login_attempt ALTER id SET DEFAULT nextval(\'failed_login_attempt_id_seq\')');
        $this->addSql('CREATE SEQUENCE interactive_choices_id_seq');
        $this->addSql('SELECT setval(\'interactive_choices_id_seq\', (SELECT MAX(id) FROM interactive_choices))');
        $this->addSql('ALTER TABLE interactive_choices ALTER id SET DEFAULT nextval(\'interactive_choices_id_seq\')');
        $this->addSql('CREATE SEQUENCE facebook_profiles_id_seq');
        $this->addSql('SELECT setval(\'facebook_profiles_id_seq\', (SELECT MAX(id) FROM facebook_profiles))');
        $this->addSql('ALTER TABLE facebook_profiles ALTER id SET DEFAULT nextval(\'facebook_profiles_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_answer_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_answer_id_seq\', (SELECT MAX(id) FROM ideas_workshop_answer))');
        $this->addSql('ALTER TABLE ideas_workshop_answer ALTER id SET DEFAULT nextval(\'ideas_workshop_answer_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_category_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_category_id_seq\', (SELECT MAX(id) FROM ideas_workshop_category))');
        $this->addSql('ALTER TABLE ideas_workshop_category ALTER id SET DEFAULT nextval(\'ideas_workshop_category_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_idea_notification_dates_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_idea_notification_dates_id_seq\', (SELECT MAX(id) FROM ideas_workshop_idea_notification_dates))');
        $this->addSql('ALTER TABLE ideas_workshop_idea_notification_dates ALTER id SET DEFAULT nextval(\'ideas_workshop_idea_notification_dates_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_consultation_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_consultation_id_seq\', (SELECT MAX(id) FROM ideas_workshop_consultation))');
        $this->addSql('ALTER TABLE ideas_workshop_consultation ALTER id SET DEFAULT nextval(\'ideas_workshop_consultation_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_theme_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_theme_id_seq\', (SELECT MAX(id) FROM ideas_workshop_theme))');
        $this->addSql('ALTER TABLE ideas_workshop_theme ALTER id SET DEFAULT nextval(\'ideas_workshop_theme_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_guideline_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_guideline_id_seq\', (SELECT MAX(id) FROM ideas_workshop_guideline))');
        $this->addSql('ALTER TABLE ideas_workshop_guideline ALTER id SET DEFAULT nextval(\'ideas_workshop_guideline_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_vote_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_vote_id_seq\', (SELECT MAX(id) FROM ideas_workshop_vote))');
        $this->addSql('ALTER TABLE ideas_workshop_vote ALTER id SET DEFAULT nextval(\'ideas_workshop_vote_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_consultation_report_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_consultation_report_id_seq\', (SELECT MAX(id) FROM ideas_workshop_consultation_report))');
        $this->addSql('ALTER TABLE ideas_workshop_consultation_report ALTER id SET DEFAULT nextval(\'ideas_workshop_consultation_report_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_need_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_need_id_seq\', (SELECT MAX(id) FROM ideas_workshop_need))');
        $this->addSql('ALTER TABLE ideas_workshop_need ALTER id SET DEFAULT nextval(\'ideas_workshop_need_id_seq\')');
        $this->addSql('CREATE SEQUENCE ideas_workshop_question_id_seq');
        $this->addSql('SELECT setval(\'ideas_workshop_question_id_seq\', (SELECT MAX(id) FROM ideas_workshop_question))');
        $this->addSql('ALTER TABLE ideas_workshop_question ALTER id SET DEFAULT nextval(\'ideas_workshop_question_id_seq\')');
        $this->addSql('CREATE SEQUENCE referent_team_member_id_seq');
        $this->addSql('SELECT setval(\'referent_team_member_id_seq\', (SELECT MAX(id) FROM referent_team_member))');
        $this->addSql('ALTER TABLE referent_team_member ALTER id SET DEFAULT nextval(\'referent_team_member_id_seq\')');
        $this->addSql('CREATE SEQUENCE procuration_managed_areas_id_seq');
        $this->addSql('SELECT setval(\'procuration_managed_areas_id_seq\', (SELECT MAX(id) FROM procuration_managed_areas))');
        $this->addSql('ALTER TABLE procuration_managed_areas ALTER id SET DEFAULT nextval(\'procuration_managed_areas_id_seq\')');
        $this->addSql('CREATE SEQUENCE legislative_district_zones_id_seq');
        $this->addSql('SELECT setval(\'legislative_district_zones_id_seq\', (SELECT MAX(id) FROM legislative_district_zones))');
        $this->addSql('ALTER TABLE legislative_district_zones ALTER id SET DEFAULT nextval(\'legislative_district_zones_id_seq\')');
        $this->addSql('CREATE SEQUENCE application_request_theme_id_seq');
        $this->addSql('SELECT setval(\'application_request_theme_id_seq\', (SELECT MAX(id) FROM application_request_theme))');
        $this->addSql('ALTER TABLE application_request_theme ALTER id SET DEFAULT nextval(\'application_request_theme_id_seq\')');
        $this->addSql('CREATE SEQUENCE application_request_technical_skill_id_seq');
        $this->addSql('SELECT setval(\'application_request_technical_skill_id_seq\', (SELECT MAX(id) FROM application_request_technical_skill))');
        $this->addSql('ALTER TABLE application_request_technical_skill ALTER id SET DEFAULT nextval(\'application_request_technical_skill_id_seq\')');
        $this->addSql('CREATE SEQUENCE application_request_volunteer_id_seq');
        $this->addSql('SELECT setval(\'application_request_volunteer_id_seq\', (SELECT MAX(id) FROM application_request_volunteer))');
        $this->addSql('ALTER TABLE application_request_volunteer ALTER id SET DEFAULT nextval(\'application_request_volunteer_id_seq\')');
        $this->addSql('CREATE SEQUENCE application_request_running_mate_id_seq');
        $this->addSql('SELECT setval(\'application_request_running_mate_id_seq\', (SELECT MAX(id) FROM application_request_running_mate))');
        $this->addSql('ALTER TABLE application_request_running_mate ALTER id SET DEFAULT nextval(\'application_request_running_mate_id_seq\')');
        $this->addSql('CREATE SEQUENCE application_request_tag_id_seq');
        $this->addSql('SELECT setval(\'application_request_tag_id_seq\', (SELECT MAX(id) FROM application_request_tag))');
        $this->addSql('ALTER TABLE application_request_tag ALTER id SET DEFAULT nextval(\'application_request_tag_id_seq\')');
        $this->addSql('CREATE SEQUENCE articles_categories_id_seq');
        $this->addSql('SELECT setval(\'articles_categories_id_seq\', (SELECT MAX(id) FROM articles_categories))');
        $this->addSql('ALTER TABLE articles_categories ALTER id SET DEFAULT nextval(\'articles_categories_id_seq\')');
        $this->addSql('CREATE SEQUENCE home_blocks_id_seq');
        $this->addSql('SELECT setval(\'home_blocks_id_seq\', (SELECT MAX(id) FROM home_blocks))');
        $this->addSql('ALTER TABLE home_blocks ALTER id SET DEFAULT nextval(\'home_blocks_id_seq\')');
        $this->addSql('CREATE SEQUENCE committees_membership_histories_id_seq');
        $this->addSql('SELECT setval(\'committees_membership_histories_id_seq\', (SELECT MAX(id) FROM committees_membership_histories))');
        $this->addSql('ALTER TABLE committees_membership_histories ALTER id SET DEFAULT nextval(\'committees_membership_histories_id_seq\')');
        $this->addSql('CREATE SEQUENCE adherent_email_subscription_histories_id_seq');
        $this->addSql('SELECT setval(\'adherent_email_subscription_histories_id_seq\', (SELECT MAX(id) FROM adherent_email_subscription_histories))');
        $this->addSql('ALTER TABLE adherent_email_subscription_histories ALTER id SET DEFAULT nextval(\'adherent_email_subscription_histories_id_seq\')');
        $this->addSql('CREATE SEQUENCE administrator_export_history_id_seq');
        $this->addSql('SELECT setval(\'administrator_export_history_id_seq\', (SELECT MAX(id) FROM administrator_export_history))');
        $this->addSql('ALTER TABLE administrator_export_history ALTER id SET DEFAULT nextval(\'administrator_export_history_id_seq\')');
        $this->addSql('CREATE SEQUENCE committee_merge_histories_id_seq');
        $this->addSql('SELECT setval(\'committee_merge_histories_id_seq\', (SELECT MAX(id) FROM committee_merge_histories))');
        $this->addSql('ALTER TABLE committee_merge_histories ALTER id SET DEFAULT nextval(\'committee_merge_histories_id_seq\')');
        $this->addSql('CREATE SEQUENCE medias_id_seq');
        $this->addSql('SELECT setval(\'medias_id_seq\', (SELECT MAX(id) FROM medias))');
        $this->addSql('ALTER TABLE medias ALTER id SET DEFAULT nextval(\'medias_id_seq\')');
        $this->addSql('CREATE SEQUENCE referent_area_id_seq');
        $this->addSql('SELECT setval(\'referent_area_id_seq\', (SELECT MAX(id) FROM referent_area))');
        $this->addSql('ALTER TABLE referent_area ALTER id SET DEFAULT nextval(\'referent_area_id_seq\')');
        $this->addSql('CREATE SEQUENCE republican_silence_id_seq');
        $this->addSql('SELECT setval(\'republican_silence_id_seq\', (SELECT MAX(id) FROM republican_silence))');
        $this->addSql('ALTER TABLE republican_silence ALTER id SET DEFAULT nextval(\'republican_silence_id_seq\')');
        $this->addSql('CREATE SEQUENCE facebook_videos_id_seq');
        $this->addSql('SELECT setval(\'facebook_videos_id_seq\', (SELECT MAX(id) FROM facebook_videos))');
        $this->addSql('ALTER TABLE facebook_videos ALTER id SET DEFAULT nextval(\'facebook_videos_id_seq\')');
        $this->addSql('CREATE SEQUENCE emails_id_seq');
        $this->addSql('SELECT setval(\'emails_id_seq\', (SELECT MAX(id) FROM emails))');
        $this->addSql('ALTER TABLE emails ALTER id SET DEFAULT nextval(\'emails_id_seq\')');
        $this->addSql('CREATE SEQUENCE social_shares_id_seq');
        $this->addSql('SELECT setval(\'social_shares_id_seq\', (SELECT MAX(id) FROM social_shares))');
        $this->addSql('ALTER TABLE social_shares ALTER id SET DEFAULT nextval(\'social_shares_id_seq\')');
        $this->addSql('CREATE SEQUENCE assessor_managed_areas_id_seq');
        $this->addSql('SELECT setval(\'assessor_managed_areas_id_seq\', (SELECT MAX(id) FROM assessor_managed_areas))');
        $this->addSql('ALTER TABLE assessor_managed_areas ALTER id SET DEFAULT nextval(\'assessor_managed_areas_id_seq\')');
        $this->addSql('CREATE SEQUENCE newsletter_subscriptions_id_seq');
        $this->addSql('SELECT setval(\'newsletter_subscriptions_id_seq\', (SELECT MAX(id) FROM newsletter_subscriptions))');
        $this->addSql('ALTER TABLE newsletter_subscriptions ALTER id SET DEFAULT nextval(\'newsletter_subscriptions_id_seq\')');
        $this->addSql('CREATE SEQUENCE referent_managed_areas_id_seq');
        $this->addSql('SELECT setval(\'referent_managed_areas_id_seq\', (SELECT MAX(id) FROM referent_managed_areas))');
        $this->addSql('ALTER TABLE referent_managed_areas ALTER id SET DEFAULT nextval(\'referent_managed_areas_id_seq\')');
        $this->addSql('CREATE SEQUENCE donation_transactions_id_seq');
        $this->addSql('SELECT setval(\'donation_transactions_id_seq\', (SELECT MAX(id) FROM donation_transactions))');
        $this->addSql('ALTER TABLE donation_transactions ALTER id SET DEFAULT nextval(\'donation_transactions_id_seq\')');
        $this->addSql('CREATE SEQUENCE formation_files_id_seq');
        $this->addSql('SELECT setval(\'formation_files_id_seq\', (SELECT MAX(id) FROM formation_files))');
        $this->addSql('ALTER TABLE formation_files ALTER id SET DEFAULT nextval(\'formation_files_id_seq\')');
        $this->addSql('CREATE SEQUENCE formation_axes_id_seq');
        $this->addSql('SELECT setval(\'formation_axes_id_seq\', (SELECT MAX(id) FROM formation_axes))');
        $this->addSql('ALTER TABLE formation_axes ALTER id SET DEFAULT nextval(\'formation_axes_id_seq\')');
        $this->addSql('CREATE SEQUENCE order_sections_id_seq');
        $this->addSql('SELECT setval(\'order_sections_id_seq\', (SELECT MAX(id) FROM order_sections))');
        $this->addSql('ALTER TABLE order_sections ALTER id SET DEFAULT nextval(\'order_sections_id_seq\')');
        $this->addSql('CREATE SEQUENCE citizen_project_committee_supports_id_seq');
        $this->addSql('SELECT setval(\'citizen_project_committee_supports_id_seq\', (SELECT MAX(id) FROM citizen_project_committee_supports))');
        $this->addSql('ALTER TABLE citizen_project_committee_supports ALTER id SET DEFAULT nextval(\'citizen_project_committee_supports_id_seq\')');
        $this->addSql('CREATE SEQUENCE events_registrations_id_seq');
        $this->addSql('SELECT setval(\'events_registrations_id_seq\', (SELECT MAX(id) FROM events_registrations))');
        $this->addSql('ALTER TABLE events_registrations ALTER id SET DEFAULT nextval(\'events_registrations_id_seq\')');
        $this->addSql('CREATE SEQUENCE banned_adherent_id_seq');
        $this->addSql('SELECT setval(\'banned_adherent_id_seq\', (SELECT MAX(id) FROM banned_adherent))');
        $this->addSql('ALTER TABLE banned_adherent ALTER id SET DEFAULT nextval(\'banned_adherent_id_seq\')');
        $this->addSql('CREATE SEQUENCE jecoute_question_id_seq');
        $this->addSql('SELECT setval(\'jecoute_question_id_seq\', (SELECT MAX(id) FROM jecoute_question))');
        $this->addSql('ALTER TABLE jecoute_question ALTER id SET DEFAULT nextval(\'jecoute_question_id_seq\')');
        $this->addSql('CREATE SEQUENCE jecoute_choice_id_seq');
        $this->addSql('SELECT setval(\'jecoute_choice_id_seq\', (SELECT MAX(id) FROM jecoute_choice))');
        $this->addSql('ALTER TABLE jecoute_choice ALTER id SET DEFAULT nextval(\'jecoute_choice_id_seq\')');
        $this->addSql('CREATE SEQUENCE jecoute_data_survey_id_seq');
        $this->addSql('SELECT setval(\'jecoute_data_survey_id_seq\', (SELECT MAX(id) FROM jecoute_data_survey))');
        $this->addSql('ALTER TABLE jecoute_data_survey ALTER id SET DEFAULT nextval(\'jecoute_data_survey_id_seq\')');
        $this->addSql('CREATE SEQUENCE jecoute_data_answer_id_seq');
        $this->addSql('SELECT setval(\'jecoute_data_answer_id_seq\', (SELECT MAX(id) FROM jecoute_data_answer))');
        $this->addSql('ALTER TABLE jecoute_data_answer ALTER id SET DEFAULT nextval(\'jecoute_data_answer_id_seq\')');
        $this->addSql('CREATE SEQUENCE deputy_managed_users_message_id_seq');
        $this->addSql('SELECT setval(\'deputy_managed_users_message_id_seq\', (SELECT MAX(id) FROM deputy_managed_users_message))');
        $this->addSql('ALTER TABLE deputy_managed_users_message ALTER id SET DEFAULT nextval(\'deputy_managed_users_message_id_seq\')');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE redirections ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE adherent_reset_password_tokens ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE newsletter_invitations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE invitations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE je_marche_reports ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE live_links ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE adherent_change_email_token ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE failed_login_attempt ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE facebook_profiles ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_idea_notification_dates ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_consultation ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_consultation_report ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE adherent_activation_keys ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE facebook_videos ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE emails ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE newsletter_subscriptions ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE biography_executive_office_member ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE banned_adherent ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE donations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE donation_transactions ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE geo_data ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE coordinator_managed_areas ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE procuration_managed_areas ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE assessor_managed_areas ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE jecoute_managed_areas ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE municipal_chief_areas ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE board_member ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE events_invitations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE referent_managed_users_message ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE referent_area ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE organizational_chart_item ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE referent ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE referent_person_link ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE pages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE web_hooks ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE referent_space_access_information ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE timeline_manifestos ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE timeline_profiles ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE timeline_themes ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE timeline_measures ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE proposals ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_articles ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE order_sections ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE committees_memberships ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE assessor_requests ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE vote_place ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE committee_feed_item ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE turnkey_projects_files ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE mooc_attachment_link ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE mooc_elements ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE mooc_attachment_file ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE mooc ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE mooc_chapter ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE reports ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE custom_search_results ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE articles_categories ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE articles ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE proposals_themes ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE adherent_message_filters ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE mailchimp_campaign_report ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE adherent_messages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE mailchimp_campaign ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE citizen_project_memberships ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE oauth_access_tokens ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE oauth_refresh_tokens ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE oauth_auth_codes ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE oauth_clients ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE user_authorizations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chez_vous_regions ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chez_vous_markers ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chez_vous_departments ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chez_vous_cities ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chez_vous_measures ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE user_documents ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_answer ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_thread ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_comment ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_vote ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_category ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_theme ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_idea ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_need ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_guideline ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ideas_workshop_question ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE referent_team_member ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE clarifications ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE application_request_technical_skill ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE application_request_volunteer ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE application_request_theme ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE application_request_tag ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE application_request_running_mate ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE procuration_requests ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE home_blocks ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE committees_membership_histories ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE subscription_type ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE adherent_email_subscription_histories ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE administrator_export_history ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE committee_merge_histories ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE republican_silence ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE interactive_invitations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE interactive_choices ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE procuration_proxies ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE social_share_categories ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE social_shares ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE referent_managed_areas ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE formation_modules ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE formation_files ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE formation_axes ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE committees ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE citizen_project_committee_supports ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE legislative_district_zones ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE medias ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE legislative_candidates ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ton_macron_friend_invitations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ton_macron_choices ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE events ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE events_registrations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE turnkey_projects ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE citizen_projects ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE administrators ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE jecoute_question ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE jecoute_survey ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE jecoute_survey_question ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE jecoute_data_survey ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE jecoute_data_answer ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE jecoute_choice ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE districts ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE adherents ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE deputy_managed_users_message ALTER id DROP DEFAULT');
    }
}
