<?php

declare(strict_types=1);

namespace App\AdherentMessage\Stats;

use App\JeMengage\Hit\EventTypeEnum;
use App\JeMengage\Hit\SourceGroupEnum;
use App\JeMengage\Hit\TargetTypeEnum;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Uid\Uuid;

class EmailAppHitWriter
{
    public function __construct(private readonly EntityManagerInterface $entityManager)
    {
    }

    public function buildOpenRow(int $adherentId, string $objectId, \DateTimeImmutable $occurredAtUtc): array
    {
        return [
            'adherent_id' => $adherentId,
            'event_type' => EventTypeEnum::Open->value,
            'source' => 'email',
            'object_type' => TargetTypeEnum::Publication->value,
            'object_id' => $objectId,
            'app_date' => $occurredAtUtc->format('Y-m-d H:i:s'),
            'fingerprint' => $this->buildFingerprint([$adherentId, 'email', 'open', $objectId, $occurredAtUtc->format('c')]),
        ];
    }

    public function buildClickRow(int $adherentId, string $objectId, string $url, \DateTimeImmutable $occurredAtUtc): array
    {
        return [
            'adherent_id' => $adherentId,
            'event_type' => EventTypeEnum::Click->value,
            'source' => 'email',
            'target_url' => $url,
            'object_type' => TargetTypeEnum::Publication->value,
            'object_id' => $objectId,
            'app_date' => $occurredAtUtc->format('Y-m-d H:i:s'),
            'fingerprint' => $this->buildFingerprint([$adherentId, 'email', 'click', $url, $objectId, $occurredAtUtc->format('c')]),
        ];
    }

    public function insertHits(array $rows): void
    {
        if (!$rows) {
            return;
        }

        $conn = $this->entityManager->getConnection();

        // Filter out rows whose fingerprint already exists in the database
        $fingerprints = array_column($rows, 'fingerprint');
        $existing = [];

        foreach (array_chunk($fingerprints, 1000) as $chunk) {
            $placeholders = implode(',', array_fill(0, \count($chunk), '?'));
            $result = $conn->fetchFirstColumn("SELECT fingerprint FROM app_hit WHERE fingerprint IN ($placeholders)", $chunk);
            foreach ($result as $fp) {
                $existing[$fp] = true;
            }
        }

        $rows = array_filter($rows, static fn (array $r) => !isset($existing[$r['fingerprint']]));

        if (!$rows) {
            return;
        }

        // Sort by fingerprint to avoid deadlocks
        usort($rows, static fn (array $a, array $b) => strcmp($a['fingerprint'] ?? '', $b['fingerprint'] ?? ''));

        $autoCols = ['uuid', 'activity_session_uuid', 'created_at', 'updated_at', 'source_group'];
        $dynamicCols = array_keys(reset($rows));
        $cols = array_values(array_unique(array_merge($autoCols, $dynamicCols)));

        $placeholders = [];
        $params = [];

        $nowUtc = new \DateTimeImmutable('now', new \DateTimeZone('UTC'))->format('Y-m-d H:i:s');

        foreach ($rows as $r) {
            $autoGeneratedData = [
                'uuid' => Uuid::v4()->toRfc4122(),
                'activity_session_uuid' => Uuid::v4()->toRfc4122(),
                'created_at' => $nowUtc,
                'updated_at' => $nowUtc,
                'source_group' => SourceGroupEnum::Email->value,
            ];

            $placeholders[] = '('.implode(',', array_fill(0, \count($cols), '?')).')';

            foreach ($cols as $c) {
                if (\array_key_exists($c, $autoGeneratedData)) {
                    $params[] = $autoGeneratedData[$c];
                } else {
                    $params[] = $r[$c] ?? null;
                }
            }
        }

        // Native UPSERT: ON DUPLICATE KEY on the unique fingerprint makes a redelivered event idempotent.
        $sql = \sprintf(
            'INSERT INTO app_hit (%s) VALUES %s ON DUPLICATE KEY UPDATE fingerprint = VALUES(fingerprint)',
            implode(',', $cols),
            implode(',', $placeholders)
        );

        $conn->executeStatement($sql, $params);
    }

    private function buildFingerprint(array $parts): string
    {
        return hash('sha256', implode('|', $parts));
    }
}
