framework:
    messenger:
        transports:
            default:
                retry_strategy:
                    max_retries: 0
            pap:
                retry_strategy:
                    max_retries: 0

            mailchimp_sync:
                retry_strategy:
                    max_retries: 0

            mailchimp_campaign:
                retry_strategy:
                    max_retries: 0

            mailer:
                retry_strategy:
                    max_retries: 0
