web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    profiler: { only_exceptions: false }

services:
    profiler.storage:
        class: App\Profiler\Storage\RedisProfilerStorage
        arguments:
            - '@snc_redis.default'
            - 3600
