services:
    Google\Cloud\Storage\StorageClient: ~

flysystem:
    storages:
        default.storage:
            adapter: 'gcloud'
            options:
                client: 'Google\Cloud\Storage\StorageClient'
                bucket: '%env(GCLOUD_BUCKET)%'

        national_event.storage:
            adapter: 'gcloud'
            options:
                client: 'Google\Cloud\Storage\StorageClient'
                bucket: '%env(GCLOUD_NATIONAL_EVENT_BUCKET)%'
                visibility_handler: 'flysystem.adapter.gcloud.visibility.uniform'
