services:
    Google\Cloud\Storage\StorageClient: ~

flysystem:
    storages:
        default.storage:
            adapter: 'gcloud'
            options:
                client: 'Google\Cloud\Storage\StorageClient'
                bucket: '%env(GCLOUD_BUCKET)%'

        national_event.storage:
            adapter: 'gcloud'
            options:
                client: 'Google\Cloud\Storage\StorageClient'
                bucket: '%env(GCLOUD_NATIONAL_EVENT_BUCKET)%'
                visibility_handler: 'flysystem.adapter.gcloud.visibility.uniform'

        public_user_file.storage:
            adapter: 'gcloud'
            public_url: 'https://%env(GCLOUD_PUBLIC_USER_FILE_BUCKET)%/public'
            options:
                client: 'Google\Cloud\Storage\StorageClient'
                bucket: '%env(GCLOUD_PUBLIC_USER_FILE_BUCKET)%'
                prefix: 'public'
                visibility_handler: 'flysystem.adapter.gcloud.visibility.uniform'
