name: Setup composer
description: Setup composer and install dependencies

inputs:
    skip-install:
        description: Set to 'true' to skip composer install (when cache is already restored)
        required: false
        default: 'false'

runs:
    using: composite
    steps:
        - name: Setup PHP ${{ env.PHP_VERSION }}
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ env.PHP_VERSION }}
              coverage: none

        - name: Install composer dependencies
          if: inputs.skip-install != 'true'
          shell: bash
          run: composer install
