name: docker login
description: Authenticate with docker on registry

runs:
  using: composite
  steps:
    - uses: google-github-actions/auth@v0.4.1
      with:
        credentials_json: ${{ env.REGISTRY_SERVICE_ACCOUNT_KEY }}

    - shell: bash
      run: |-
        gcloud auth --quiet configure-docker $REGISTRY_HOST
