name: docker login
description: Authenticate with docker on registry

runs:
  using: composite
  steps:
    - uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ env.GCP_SA_KEY_GCR_PUSHER }}

    - shell: bash
      run: |-
        gcloud auth --quiet configure-docker $REGISTRY_HOST
