name: Dependencies cache
description: Restore dependencies from cache

outputs:
    composer-cache-hit:
        description: 'Whether the composer cache was hit exactly (true/false)'
        value: ${{ steps.composer-cache.outputs.cache-hit }}

runs:
    using: composite
    steps:
        - name: Cache composer
          id: composer-cache
          uses: actions/cache@v5
          with:
              path: vendor/
              key: cache-${{ env.CACHE_KEY }}-composer-${{ hashFiles('composer.lock') }}

        - name: Cache static assets
          uses: actions/cache@v5
          with:
              path: |
                  public/built/
                  public/css/
                  public/select2/
              key: cache-${{ env.CACHE_KEY }}-static-${{ hashFiles('package.json', 'pnpm-lock.yaml', 'assets/**', 'webpack.*.js') }}
