name: Setup pnpm
description: Setup Node.js + pnpm and install dependencies

runs:
    using: composite
    steps:
        - name: Install pnpm
          uses: pnpm/action-setup@v4

        - name: Setup Node.js ${{ env.NODE_VERSION }}
          uses: actions/setup-node@v4
          with:
              node-version: ${{ env.NODE_VERSION }}
              cache: pnpm

        - name: Install dependencies
          shell: bash
          run: pnpm install --frozen-lockfile
