name: CI & CD

on:
    push:
    release:
        types: [published]

env:
    DOCKER_BUILDKIT: 1
    DOCKER_COMPOSE_ARGS: -f compose.yml -f compose.ci.yml
    EXEC_ARGS: -T
    # Update this to force cache reset
    CACHE_KEY: ${{ secrets.CACHE_KEY }}
    HASH: ${{ github.sha }}
    TAG: ${{ github.ref_name }}

    NODE_VERSION: 22.x
    PHP_VERSION: 8.5

    REGISTRY: ${{ secrets.GCP_HOST_GCR }}/${{ secrets.GCP_REGISTRY_PROJECT_ID }}/${{ vars.GCR_PROJECT_NAME }}
    REGISTRY_HOST: ${{ secrets.GCP_HOST_GCR }}
    GCP_SA_KEY_GCR_PUSHER: ${{ secrets.GCP_SA_KEY_GCR_PUSHER }}

concurrency:
    group: ${{ github.ref_name }}
    cancel-in-progress: true

jobs:
    build:
        name: Build dev
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v6

            - name: Cache composer
              id: composer-cache
              uses: actions/cache@v5
              with:
                  path: vendor/
                  key: cache-${{ env.CACHE_KEY }}-composer-${{ hashFiles('composer.lock') }}

            - uses: ./.github/actions/docker-login

            - uses: ./.github/actions/docker-pull
              with:
                  hash: ${{ hashFiles('Dockerfile', 'docker/*') }}

            - uses: ./.github/actions/build
              with:
                  hash: ${{ hashFiles('Dockerfile', 'docker/*') }}
                  skip-composer-install: ${{ steps.composer-cache.outputs.cache-hit }}

            - uses: ./.github/actions/docker-push
              with:
                  hash: ${{ hashFiles('Dockerfile', 'docker/*') }}

    build-static:
        name: Build assets
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v6

            - name: Cache static assets
              id: static-cache
              uses: actions/cache@v5
              with:
                  path: |
                      public/built/
                      public/css/
                      public/select2/
                  key: cache-${{ env.CACHE_KEY }}-static-${{ hashFiles('package.json', 'pnpm-lock.yaml', 'assets/**', 'webpack.*.js') }}

            - name: Setup pnpm
              if: steps.static-cache.outputs.cache-hit != 'true'
              uses: ./.github/actions/setup-pnpm

            - name: Build static assets
              if: steps.static-cache.outputs.cache-hit != 'true'
              run: pnpm build-prod

    lint:
        name: Lint
        runs-on: ubuntu-24.04
        if: github.ref_name != 'master' || vars.SKIP_TESTS_ON_DEPLOY != 'true'
        env:
            EXEC:
            RUN_NODE:
        steps:
            - uses: actions/checkout@v6

            - name: Cache composer
              id: composer-cache
              uses: actions/cache@v5
              with:
                  path: vendor/
                  key: cache-${{ env.CACHE_KEY }}-composer-${{ hashFiles('composer.lock') }}

            - name: Cache PHP CS Fixer
              uses: actions/cache@v5
              with:
                  path: var/.php_cs
                  key: cache-${{ env.CACHE_KEY }}-phpcsfixer-${{ github.sha }}
                  restore-keys: |
                      cache-${{ env.CACHE_KEY }}-phpcsfixer-

            - name: Cache PHPStan
              uses: actions/cache@v5
              with:
                  path: var/phpstan-tmp/
                  key: cache-${{ env.CACHE_KEY }}-phpstan-${{ github.sha }}
                  restore-keys: |
                      cache-${{ env.CACHE_KEY }}-phpstan-

            - uses: ./.github/actions/setup-composer
              with:
                  skip-install: ${{ steps.composer-cache.outputs.cache-hit }}
            - uses: ./.github/actions/setup-pnpm

            - name: Validate composer.json and composer.lock
              if: ${{ !cancelled() }}
              run: composer validate --no-check-all --no-check-publish

            - name: PHP Coding Standards Fixer
              if: ${{ !cancelled() }}
              run: make phpcs

            - name: Lint YAML files
              if: ${{ !cancelled() }}
              run: make ly

            - name: Lint Twig files
              if: ${{ !cancelled() }}
              run: make lt

            - name: Lint container
              if: ${{ !cancelled() }}
              run: make lc

            - name: ESLint
              if: ${{ !cancelled() }}
              run: make lj

            - name: Prettier
              if: ${{ !cancelled() }}
              run: make lp

            - name: PHPStan - PHP Static Analysis Tool
              if: ${{ !cancelled() }}
              run: make phpstan

            - name: Composer Security Audit
              if: ${{ !cancelled() }}
              continue-on-error: true
              run: composer audit --abandoned=report

    phpunit:
        name: PHPUnit
        runs-on: ubuntu-24.04
        needs: [build, build-static]
        if: github.ref_name != 'master' || vars.SKIP_TESTS_ON_DEPLOY != 'true'

        steps:
            - uses: actions/checkout@v6

            - id: deps-cache
              uses: ./.github/actions/dependencies-cache

            - name: Cache PHPUnit
              uses: actions/cache@v5
              with:
                  path: var/.phpunit.cache/
                  key: cache-${{ env.CACHE_KEY }}-phpunit-${{ github.sha }}
                  restore-keys: |
                      cache-${{ env.CACHE_KEY }}-phpunit-

            - uses: ./.github/actions/docker-login

            - uses: ./.github/actions/docker-pull
              with:
                  hash: ${{ hashFiles('Dockerfile', 'docker/*') }}

            - uses: ./.github/actions/build
              with:
                  hash: ${{ hashFiles('Dockerfile', 'docker/*') }}
                  skip-composer-install: ${{ steps.deps-cache.outputs.composer-cache-hit }}
                  extra-containers: db redis rabbitmq
                  keys: true
                  cache-warmup: true

            - name: Prepare app (assets, cache, db, rabbitmq)
              run: make tfp-rabbitmq tfp-db

            - env:
                  PHPUNIT_ARGS: --log-junit ./phpunit/junit.xml
              run: |-
                  make test-phpunit

    behat:
        name: Behat
        runs-on: ubuntu-24.04
        needs: [build, build-static]
        if: github.ref_name != 'master' || vars.SKIP_TESTS_ON_DEPLOY != 'true'

        steps:
            - uses: actions/checkout@v6

            - id: deps-cache
              uses: ./.github/actions/dependencies-cache

            - uses: ./.github/actions/docker-login

            - uses: ./.github/actions/docker-pull
              with:
                  hash: ${{ hashFiles('Dockerfile', 'docker/*') }}

            - uses: ./.github/actions/build
              with:
                  hash: ${{ hashFiles('Dockerfile', 'docker/*') }}
                  skip-composer-install: ${{ steps.deps-cache.outputs.composer-cache-hit }}
                  extra-containers: db redis rabbitmq
                  keys: true
                  cache-warmup: true

            - name: Prepare app (assets, cache, db, rabbitmq)
              run: make tfp-rabbitmq tfp-db

            - env:
                  BEHAT_ARGS: --suite=default -vvv --colors -f progress -o std -f junit -o ./behat --
              run: |-
                  make test-behat

    behat-selenium:
        name: Behat/Selenium
        runs-on: ubuntu-24.04
        needs: [build, build-static]
        if: github.ref_name != 'master' || vars.SKIP_TESTS_ON_DEPLOY != 'true'
        strategy:
            fail-fast: false
            matrix:
                tags:
                    - '@javascript1'
                    - '@javascript2'
                    - '@ux-component'

        steps:
            - uses: actions/checkout@v6

            - id: deps-cache
              uses: ./.github/actions/dependencies-cache

            - uses: ./.github/actions/docker-login

            - uses: ./.github/actions/docker-pull
              with:
                  hash: ${{ hashFiles('Dockerfile', 'docker/*') }}

            - uses: ./.github/actions/build
              with:
                  hash: ${{ hashFiles('Dockerfile', 'docker/*') }}
                  skip-composer-install: ${{ steps.deps-cache.outputs.composer-cache-hit }}
                  extra-containers: db redis rabbitmq selenium
                  keys: true

            - name: Prepare app (assets, cache, db, rabbitmq)
              run: make tfp-rabbitmq tfp-db

            - env:
                  BEHAT_ARGS: --suite=javascript --tags="${{ matrix.tags }}" -vvv --colors -f progress -o std -f junit -o ./behat --
              run: |-
                  make test-behat

            - uses: actions/upload-artifact@v7
              if: failure()
              with:
                  name: behat-selenium-screenshots-${{ matrix.tags }}
                  path: var/behat/
                  retention-days: 1

    docker-build-push-gcr:
        name: Build prod & push on registry
        runs-on: ubuntu-24.04
        needs: [lint, phpunit, behat, behat-selenium]
        if: |
            always() &&
            (github.ref_name == 'master' || github.event_name == 'release') &&
            !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')

        steps:
            - uses: actions/checkout@v6

            - name: Cache composer
              uses: actions/cache@v5
              with:
                  path: vendor/
                  key: cache-${{ env.CACHE_KEY }}-composer-${{ hashFiles('composer.lock') }}

            - name: Cache static assets
              uses: actions/cache@v5
              with:
                  path: |
                      public/built/
                      public/css/
                      public/select2/
                  key: cache-${{ env.CACHE_KEY }}-static-${{ github.sha }}

            - uses: ./.github/actions/docker-login

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - run: perl -pi -e "s/default/${{ github.sha }}/g" ./config/packages/app_version.php

            - run: |-
                  docker buildx build \
                      --push \
                      --cache-from=type=gha,scope=prod \
                      --cache-from=type=gha,scope=dev \
                      --cache-from=type=registry,ref=${{ env.REGISTRY }}:${{ env.TAG }} \
                      --cache-from=type=registry,ref=${{ env.REGISTRY }}:dev-${{ hashFiles('Dockerfile', 'docker/*') }} \
                      --cache-to=type=gha,scope=prod,mode=max \
                      --tag ${{ env.REGISTRY }}:${{ env.TAG }}-${{ env.HASH }} \
                      --tag ${{ env.REGISTRY }}:${{ env.TAG }} \
                      --target=frankenphp_base \
                      --build-arg BUILDKIT_INLINE_CACHE=1 \
                      .

    deploy-staging:
        name: Deploy Staging
        runs-on: ubuntu-24.04
        needs: [docker-build-push-gcr]
        environment: staging
        if: always() && needs.docker-build-push-gcr.result == 'success' && github.ref_name == 'master'

        steps:
            - uses: actions/checkout@v6

            - name: Create Sentry release
              uses: getsentry/action-release@v3
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
              with:
                  environment: staging
                  ignore_missing: true
                  ignore_empty: true

            - uses: google-github-actions/auth@v3
              with:
                  credentials_json: ${{ secrets.GCP_SA_KEY_GKE_DEPLOYER }}

            - uses: google-github-actions/get-gke-credentials@v3
              with:
                  cluster_name: ${{ secrets.GKE_CLUSTER }}
                  location: ${{ secrets.GKE_REGION }}

            - run: |-
                  for GKE_DEPLOYMENT in $(echo ${{ vars.GKE_DEPLOYMENTS }}); do
                    kubectl set image deployment/$GKE_DEPLOYMENT ${{ secrets.GKE_CONTAINER }}=${{ env.REGISTRY }}:${{ env.TAG }}-${{ env.HASH }}
                  done
