name: Remove old unused images from registry
on:
  schedule:
    - cron: "0 6 * * *"
env:
  INTERVAL_OLD_IMAGES: ${{ secrets.CLEANUP_OLD_IMAGES_TIME_DIFF }}

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:

      - uses: google-github-actions/auth@v0.4.2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_GCR_PUSHER }}

      - run: |
          limitDate=$(date "+%Y-%m-%d %H:%M:%S" -d "$INTERVAL_OLD_IMAGES")

          digests=$(gcloud container images list-tags $IMAGE \
          --filter="timestamp.datetime < '$limitDate'" \
          --format="get(digest)")

          for digest in $digests; do
          (
            gcloud container images delete --quiet --force-delete-tags $IMAGE@$digest
          )
          done
