name: Remove old unused images from registry

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch: # allows for manual invocation

env:
  IMAGE: ${{ secrets.GCP_HOST_GCR }}/${{ secrets.GCP_REGISTRY_PROJECT_ID }}/${{ secrets.REGISTRY_NAME }}

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GCP_HOST_GCR }}
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY_GCR_PUSHER }}

      - uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=${{ env.IMAGE }}
            -grace=${{ secrets.INTERVAL_OLD_IMAGES }}
