name: Setup node
description: Setup node and install yarn dependencies

runs:
  using: composite
  steps:
    - name: Setup node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install yarn dependencies
      shell: bash
      run: yarn install
